/-
Copyright 2026 The Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Oliver Butterley
-/
import Curve25519Dalek.Math.Edwards.Curve
import Utils.GrindBench

/-! # Ed25519 Eight-Torsion Subgroup

The eight-torsion subgroup E[8] of the Ed25519 Edwards curve is cyclic,
generated by a point of order 8. These are purely mathematical facts,
independent of any implementation representation.
-/

-- `native_decide` is required for group law computations over large field elements;
-- `decide` times out on these.
set_option linter.style.nativeDecide false

namespace Edwards

/-- Generator of the eight-torsion subgroup of Ed25519. -/
def eightTorsionGen : Point Ed25519 where
  x := 14399317868200118260347934320527232580618823971194345261214217575416788799818
  y := 55188659117513257062467267217118295137698188065244968500265048394206261417927
  on_curve := by decide

theorem eight_nsmul_gen_eq_zero : 8 • eightTorsionGen = 0 := by native_decide

theorem four_nsmul_gen_ne_zero : 4 • eightTorsionGen ≠ 0 := by native_decide

/-- The i-th point of the eight-torsion subgroup, i.e., the precomputed value of
    `i • eightTorsionGen`. -/
def eightTorsionPoints : Fin 8 → Point Ed25519
  | 0 => { x := 0, y := 1, on_curve := by decide }
  | 1 => eightTorsionGen
  | 2 => {
    x := 38214883241950591754978413199355411911188925816896391856984770930832735035197
    y := 0
    on_curve := by decide }
  | 3 => {
    x := 14399317868200118260347934320527232580618823971194345261214217575416788799818
    y := 2707385501144840649318225287225658788936804267575313519463743609750303402022
    on_curve := by decide }
  | 4 => {
    x := 0
    y := 57896044618658097711785492504343953926634992332820282019728792003956564819948
    on_curve := by decide }
  | 5 => {
    x := 43496726750457979451437558183816721346016168361625936758514574428539776020131
    y := 2707385501144840649318225287225658788936804267575313519463743609750303402022
    on_curve := by decide }
  | 6 => {
    x := 19681161376707505956807079304988542015446066515923890162744021073123829784752
    y := 0
    on_curve := by decide }
  | 7 => {
    x := 43496726750457979451437558183816721346016168361625936758514574428539776020131
    y := 55188659117513257062467267217118295137698188065244968500265048394206261417927
    on_curve := by decide }

@[simp]
theorem nsmul_eightTorsionGen_eq (i : Fin 8) :
    (i : ℕ) • eightTorsionGen = eightTorsionPoints i := by
  fin_cases i <;> native_decide

/-- Helper for spec proofs: if `gen_pt` is the generator and `pt_i` is the i-th torsion point
    (both verified by cheap `toPoint` comparisons), then `pt_i = i • gen_pt`. -/
theorem eightTorsion_eq_nsmul (gen_pt pt_i : Point Ed25519) (i : Fin 8)
    (h_gen : gen_pt = eightTorsionGen) (h_i : pt_i = eightTorsionPoints i) :
    pt_i = (i : ℕ) • gen_pt := by
  rw [h_gen, h_i, ← nsmul_eightTorsionGen_eq]

end Edwards
